### ISSUE TITLE
Add precondition check

### ISSUE THREAD

**Issue by junchaowu** [yarpc/yarpc-java#15]
consider using lombok  or use guava's

**Comment by abhinav** [comment]
Lombok and Guava solve two different problems here with overlap only in non-null checks.

- Guava's preconditions give you `checkNotNull`, `checkArgument`, `checkState`, etc.
- Lombok gives you compile-time code generation for common boilerplate which happens to include non-null checks for things annotated `@NonNull`. An advantage of `NonNull` annotations is that static analyzers recognize those (although I would expect/hope that static analyzers also recognize Guava checks).

My recommendation is: Pick a non-null check scheme and use Lombok to reduce boilerplate regardless. Also note that if you pick Lombok for non-null checks, you may still have to use Guava for `checkArgument` and `checkState` which validate arbitrary pre-conditions about arguments/internal state.

**Comment by prashantv** [comment]
I think guava uses `NonnullByDefault`:
https://jsr-305.googlecode.com/svn/trunk/javadoc/javax/annotation/ParametersAreNonnullByDefault.html

And only parameters which can be nullable (which should be minimized) use the `@Nullable` annotation.

Do we want every parameter annotated with either `Nullable` or `NonNullable`? I'd prefer if everything was non nullable by default (and ideally with autogenerated checks) and we only annotated the `Nullable` parameters (incentivizes reducing nullable parameters too which is a plus)

**Comment by abhinav** [comment]
NonNull by default and Nullable explicitly makes sense. We should write that somewhere. I would still like Precondition checks at entry points regardless so that it fails at the first entry point where null was introduced.

**Comment by abhinav** [comment]
We'll be using lombok for this.
