### ISSUE TITLE
Implement and fill Context

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-java#171]
Currently encoding layers just use a default Context.

**Comment by vivekrsharma** [comment]
We define a Context object to begin with. For now, we keep it simple and define getHeaders(), getTimeout(), getShardKey(), getRoutingKey(), getRoutingDelegate() along with setters for all these fields on Context. 

For incoming context, we ensure to do setHeaders() to set new Header in context. Yes, this does involve keeping track of incoming and outgoing headers in the context object that is passed.

**Comment by vivekrsharma** [comment]
Client -

`Context ctx = Context.builder()
                       .setRoutingDelete(delegate)
                       .setShardKey(key)
                       .build();
client.call(ctx, "servicename",body);`

Handler -
`public CompletableFuture<ResBody> handle(Context ctx, ReqBody body) {
  System.out.println("User-ID: " + ctx.getHeader("user-id"));
  System.out.println("Caller: " + ctx.getCaller());
  Headers header = Headers.buid();
  ctx.setHeaders(headers);
  // ...
} `

**Comment by abhinav** [comment]
How are you differentiating between incoming and outgoing headers? That is,

    public CompletionStage<ResBody> handle(Context ctx, ReqBody body) {
        System.out.println(ctx.getHeader("foo"));
        
        Headers headers = ...;
        ctx.setHeaders(headers);
        
        // What gets printed here?
        System.out.println(ctx.getHeader("foo"));
        
        // Presumably this sends 'headers'
        client.call(ctx, "procedureName", body);
    }

Also, what about response headers? How are they accessed/written to in either
direction?

Plus I don't think we want Context to be mutable. That's problematic if you're
fanning out to multiple concurrent requests:

    handle(Context ctx) {
        Context ctx = ...
        
        List<CompletionStage<Result>> results = new LinkedList<>();
        for (int i = 0; i < 10; i++) {
            results.add(makeRequest(ctx, i));
        }
    }
    
    CompletionStage<Result> makeRequest(Context ctx, int i) {
        Headers headers = ...;
        ctx.setHeaders(headers);
        // what if someone else calls ctx.setHeaders between the previous line
        // and the next line?
        return client.call(ctx, ...)
    }

**Comment by vivekrsharma** [comment]
Regarding headers we need a getHeader method. The concurrency concern is a valid point. How about we generate outgoing context from incoming context and then set new headers.

```java
public CompletionStage<ResBody> handle(Context ctx, ReqBody body) {
   // Incoming headers
    System.out.println(ctx.getHeader("foo"));
    
   Context outGoingContext = new Context(ctx);
   Headers headers = ...;
   outGoingContext.set(headers);
    
    // Outgoing headers
    System.out.println(outGoingContext.getHeader("foo"));
    
    // This sends 'headers'
    client.call(outGoingContext, "procedureName", body);
}
````
Does this look good? or do we want to proceed in direction where we have different classes for incoming and outgoing?

**Comment by abhinav** [comment]
Closing in favor of https://github.com/yarpc/yarpc-java/issues/210
