### ISSUE TITLE
json: Allow ObjectMapper customization

### ISSUE THREAD

**Issue by bpon** [yarpc/yarpc-java#184]
This might be exposing too much implementation detail, but in some cases a service might want to deserialize json into custom types, or a client might want to serialize custom types into json.  We could allow consumers to provide their own ObjectMapper or decorate an existing one.

**Comment by abhinav** [comment]
An option on the JSON server and client that gives control of this is totally reasonable as long as the default case continues to work without extra effort on the users' side.
