### ISSUE TITLE
[rx] User-facing APIs should return ListenableFutures

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-java#199]
Currently, the user-facing handler APIs and clients return vanilla java.util.Futures. The only way to get a value from these is through a `get()` which won't play well with Netty's async APIs. We should change these to listenable futures so that users can use `addListener` to handle the result asynchronously.

**Comment by breerly** [comment]
Likely a stupid Q - is there a type we can return that will enable sync-looking code while taking adv of netty's ioloop? I'm thinking a coroutine like experience... does the RX lib have anything?

**Comment by abhinav** [comment]
Not that I'm aware of. Java doesn't have a way of converting a function call to an async callback. You can't do,

```
Result x = await(doSomething())
```

(Where `doSomething()` is an asynchronous operation that returns a `Future<Result>` or similar, and `await` is a function which transfers control to the IO Loop, waits for the operation to finish, and transfers control back to the call site.)

**Comment by abhinav** [comment]
Note that Java being a typed language, we can restrict how the result is accessed without the problem of runtime errors. For example, we can return a Future type that doesn't have blocking `get` methods, only callbacks. Users have no option but to use the callback to get the result and can't block the IO Loop unless they try very explicitly.

We still have the possibility of non-YARPC clients blocking the IO Loop but that's something we're gonna have to live with. As soon as they see it's a problem, users will figure out that they need to schedule the blocking task in a separate thread.
