### ISSUE TITLE
s/scheme/encoding/

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-java#2]
Let's change the terminology of `Scheme` to `Encoding` - @kriskowal used this terminology in the Open Tracing meeting the other day, and everybody knew exactly what he meant. That wouldn't have been the case for `Scheme`.

Change:

- packages/namespaces
- class names
- variable names

**Comment by breerly** [comment]
@junchaowu is this done? Please mark as resolved is so.

**Comment by junchaowu** [comment]
fixed https://github.com/yarpc/yarpc-java/pull/14.
