### ISSUE TITLE
Make lint fail if code formatter would make changes

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-java#222]
We should make our linter fail if the code formatter would make any changes to the code.

**Comment by vivekrsharma** [comment]
I didn't find an option to format the build and THEN fail it. 

We could use 

```
verifyGoogleJavaFormat {
       ignoreFailures false
}
```
This would cause the build to fail and not fix the formatting.
or use 

```
googleJavaFormat  {
       toolVersion '1.3'
        include '**/*.java'
        exclude '**/generated-sources/*'
}
```
This would fix the formatting but not fail the build.

If we do both together, 

```
verifyGoogleJavaFormat {
       ignoreFailures false
    }

     googleJavaFormat {
         toolVersion '1.3'
         include '**/*.java'
         exclude '**/generated-sources/*'
     }

tasks.googleJavaFormat.dependsOn tasks.verifyGoogleJavaFormat

```

then the build would fail on verifyGoogleJavaFormat itself.

Also I couldn't do something like 

```
  googleJavaFormat {
         toolVersion '1.3'
         include '**/*.java'
         exclude '**/generated-sources/*'
        ignoreFailures false
     }
```
I don't have very strong background in gradle and I'm not sure if I'm missing something.

**Comment by vivekrsharma** [comment]
https://github.com/yarpc/yarpc-java/pull/233
