### ISSUE TITLE
Always use `this` when referring to instance variables

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-java#23]
It helps with readability to always refer to instance variables with `this.foo` rather than just `foo`. It also helps avoid hard to track down bugs because of unexpected variable shadowing.

**Comment by junchaowu** [comment]
I have setup the IDE to throw warning if ``this`` is not append.

**Comment by junchaowu** [comment]
https://github.com/yarpc/yarpc-java/pull/29
